-- MySQL Script generated by MySQL Workbench
-- Wed Oct  8 22:51:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jlr22k
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jlr22k
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jlr22k` DEFAULT CHARACTER SET utf8 ;
USE `jlr22k` ;

-- -----------------------------------------------------
-- Table `jlr22k`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jlr22k`.`petstore` ;

CREATE TABLE IF NOT EXISTS `jlr22k`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) ZEROFILL UNSIGNED NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) UNSIGNED NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jlr22k`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jlr22k`.`customer` ;

CREATE TABLE IF NOT EXISTS `jlr22k`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT NOT NULL,
  `cus_phone` BIGINT NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jlr22k`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jlr22k`.`pet` ;

CREATE TABLE IF NOT EXISTS `jlr22k`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_age` TINYINT UNSIGNED NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `pstid_idx` (`pst_id` ASC) VISIBLE,
  INDEX `cusid_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `pstid`
    FOREIGN KEY (`pst_id`)
    REFERENCES `jlr22k`.`petstore` (`pst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cusid`
    FOREIGN KEY (`cus_id`)
    REFERENCES `jlr22k`.`customer` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `jlr22k`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `jlr22k`;
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (1, 'Paws & Whiskers Co.\n', '124 Maplewood Drive', 'tallahassee', 'fl', 32301, 8504916723, 'paws@gmail.com', 'paws.com', 12543.75, 'sadad');
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (2, 'Happy Tails Pet Supply', '58 Oak Hollow Lane', 'austin', 'tx', 78745, 9037462185, 'happy@gmail.com', 'happytails.com', 9820.40, 'asdasd');
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (3, 'The Cozy Critter Corner', '913 Birch Street', 'denver', 'co', 80204, 7148295602, 'thecozy@gmail.com', 'cozycritter.com', 15789.90, NULL);
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (4, 'FurEver Friends Pet Shop', '227 Pinecrest Avenue', 'raleigh', 'nc', 27603, 2681957439, 'furever@gmail.com', 'furever.com', 23456.30, NULL);
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (5, 'Waggin’ World', '340 Riverbend Road', 'nashville', 'tn', 37206, 4973206814, 'waggin@gmail.com', 'wagginworld.com', 18765.25, 'asdasd');
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (6, 'The Feathered Finch', '776 Harbor View Blvd', 'tampa', 'fl', 33602, 6129134728, 'feathered@gmail.com', 'feathered.com', 20987.50, NULL);
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (7, 'Purrfect Companions', '1021 Meadowlark Court', 'colombus', 'oh', 43215, 7295843160, 'purfect@gmail.com', 'purfect.com', 11234.10, NULL);
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (8, 'Critter Kingdom', '65 Sunrise Trail', 'phoenix', 'az', 85004, 3846209571, 'critter@gmail.com', 'critter.com', 17654.85, 'asdasda');
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (9, 'Tails & Scales Emporium', '432 Willow Park Drive', 'seattle', 'wa', 98109, 9462715308, 'tails@gmail.com', 'tailsandscales.com', 9456.20, NULL);
INSERT INTO `jlr22k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (10, 'Barkside Market', '890 Redwood Terrace', 'portland', 'or', 97205, 3058574926, 'barkside@gmail.com', 'barkside.com', 26890.45, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `jlr22k`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `jlr22k`;
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1001, 'josh', 'riley', '37 Sheffield Court', 'Brighton', 'ma', 02135, 4563467654, 'josh@gmail.com', 1231.32, 455.55, 'ertert');
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1002, 'andrew', 'duffy', '84 Iroquois Drive', 'Hendersen', 'ky', 42420, 5643457685, 'andrew@gmail.com', 3422.34, 3453.64, NULL);
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1003, 'madeline', 'fletcher', '124 Madison St.', 'Beverly', 'ma', 01915, 4566434567, 'madeline@gmail.com', 534.45, 43.45, NULL);
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1004, 'jc', 'sanders', '476 Proctor Dr.', 'Bloomfield', 'nj', 07003, 6586534567, 'jc@gmail.com', 3456.43, 435.34, 'wertwe');
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1005, 'bob', 'vega', '788 East Glenwood Ave.', 'Winder', 'ga', 30680, 2341346687, 'bob@gmail.com', 23.45, 5.01, NULL);
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1006, 'drake', 'hester', '917 Anderson St.', 'Maplewood', 'nj', 07040, 5778865456, 'drake@gmail.com', 66.34, 455.34, 'ewrtwert');
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1007, 'maddie', 'nguyen', '424 Thomas Street', 'Lakewood', 'nj', 08701, 4564577754, 'maddie@gmail.com', 23.53, 4556.43, NULL);
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1008, 'ava', 'dawson', '9 W. Pulaski Dr', 'Antioch', 'tn', 37013, 4564574534, 'ava@gmail.com', 4456.46, 23.45, NULL);
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1009, 'andy', 'terry', '8195 East Bay Drive', 'Bangor', 'me', 04401, 7568678655, 'andy@gmail.com', 668.44, 533.45, 'rgfergweg');
INSERT INTO `jlr22k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (1010, 'sid', 'oneal', '7038 Sage Ave.', 'Seymour', 'in', 47274, 5675735638, 'sid@gmail.com', 3434.55, 543.45, 'ergr');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jlr22k`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `jlr22k`;
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (101, 1, 1001, 'Dog', 'm', 1523.47, 1799.95, 2, 'brown', '2025/03/23', 'y', 'n', NULL);
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (102, 2, 1002, 'Cat', 'm', 987.25, 1225.50, 3, 'white', NULL, 'y', 'n', 'regeg');
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (103, 3, 1003, 'Hamster', 'm', 4500.60, 4999.99, 4, 'white', NULL, 'y', 'n', NULL);
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (104, 4, 1004, 'Parrot', 'f', 274.99, 349.75, 2, 'red', NULL, 'y', 'y', NULL);
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (105, 5, 1005, 'Rabbit', 'f', 3625.10, 4250.80, 4, 'white', '2025/07/23', 'y', 'y', 'sgdfgsdh');
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (106, 6, 1006, 'Turtle', 'f', 809.45, 950.25, 4, 'green', NULL, 'y', 'y', NULL);
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (107, 7, 1007, 'Goldfish', 'm', 6789.75, 7250.00, 3, 'gold', NULL, 'y', 'n', NULL);
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (108, 8, 1008, 'Iguana', 'f', 94.30, 129.99, 2, 'green', '2025/04/23', 'n', 'y', 'fghdfgh');
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (109, 9, 1009, 'Ferret', 'm', 2380.55, 2899.50, 2, 'brown', NULL, 'n', 'n', 'bdfghdfh');
INSERT INTO `jlr22k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (110, 10, 1010, 'Guinea Pig', 'm', 4156.88, 4699.25, 1, 'brown', NULL, 'n', 'y', NULL);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
